### ISSUE TITLE
Clarify text on MinLog

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-smart#1]
Clarify if the use of MinLog (https://www.nspop.dk/display/public/web/MinLog2+-+Leverancebeskrivelse) should be embedded into the text eventhough access in the context of IPA is focused on the Patient accesing his/her own data.

**Comment by AsgerSDSArkitekt** [comment]
Clarification has been ongoing over the summer, and we are very close to reaching the conclusion - last meeting concerning this was yesterday, and now we are awaiting the final approval. The recommendation is that a citizens/patients access to his/her own data should indeed be logged to MinLog, so this should also be the case for IPA.

**Comment by AsgerSDSArkitekt** [comment]
In Denmark, access to a patients/citizens health data, including the patients/citizens access to his/her own data, is required to be logged in the national log solution called MinLog2 (see https://www.nspop.dk/display/public/web/MinLog2+-+Min+Log+Registrering).

**Comment by jkiddo** [comment]
@AsgerSDSArkitekt would you mind copying the specific text to here as well as a specific link (the more specific the better) as I am unable to see it from the pages I've been looking at.

**Comment by jkiddo** [comment]
@AsgerSDSArkitekt I've added this text for now: https://build.fhir.org/ig/hl7dk/dk-smart/branches/master/index.html#minlog - let me know what you think.

**Comment by AsgerSDSArkitekt** [comment]
"...remember to consider when the log entries of such provided data are subject to be forwarded..." seems a bit vague. I propose to change it to "...remember that access to such provided data in many cases are subject to be logged...". And then for the link to MinLog I believe https://www.nspop.dk/display/public/web/MinLog2+-+Min+Log+Registrering is better, even though it is slightly less specific, because it makes more of the documentation visible when you follow the link.

**Comment by jkiddo** [comment]
Adjusted with https://github.com/hl7dk/dk-smart/commit/59e13d51d9943f6520245741951260ec66d6e9e4
